--COMPONENTES

--RM551987 - Eduardo Reis Braga
--RM551472 - Leonardo Ribeiro Barral
--RM551061 - Pedro Henrique Braga Alves
--RM98525 - Raphael Custodio Pabst
--RM550821 - Silvio Luiz Aranha Junior
 

--MOSTRAR TABELAS
select 'from T_RHSTU_FORMA_PAGAMENTO' as name ,count(*) from T_RHSTU_FORMA_PAGAMENTO union all
select 'from T_RHSTU_FUNCIONARIO' as name ,count(*) from T_RHSTU_FUNCIONARIO union all
select 'from T_RHSTU_LOGRADOURO' as name ,count(*) from T_RHSTU_LOGRADOURO union all
select 'from T_RHSTU_MEDICAMENTO' as name ,count(*) from T_RHSTU_MEDICAMENTO union all
select 'from T_RHSTU_MEDICO' as name ,count(*) from T_RHSTU_MEDICO union all
select 'from T_RHSTU_MOTORISTA' as name ,count(*) from T_RHSTU_MOTORISTA union all
select 'from T_RHSTU_PACIENTE' as name ,count(*) from T_RHSTU_PACIENTE union all
select 'from T_RHSTU_PACIENTE_PLANO_SAUDE' as name ,count(*) from T_RHSTU_PACIENTE_PLANO_SAUDE union all
select 'from T_RHSTU_PLANO_SAUDE' as name ,count(*) from T_RHSTU_PLANO_SAUDE union all
select 'from T_RHSTU_PRESCRICAO_MEDICA' as name ,count(*) from T_RHSTU_PRESCRICAO_MEDICA union all
select 'from T_RHSTU_TELEFONE_PACIENTE' as name ,count(*) from T_RHSTU_TELEFONE_PACIENTE union all
select 'from T_RHSTU_TIPO_CONTATO' as name ,count(*) from T_RHSTU_TIPO_CONTATO union all
select 'from T_RHSTU_UNID_HOSPITALAR' as name ,count(*) from T_RHSTU_UNID_HOSPITALAR union all
select 'from T_RHSTU_BAIRRO' as name ,count(*) from T_RHSTU_BAIRRO union all
select 'from T_RHSTU_CIDADE' as name ,count(*) from T_RHSTU_CIDADE union all
select 'from T_RHSTU_CONSULTA' as name ,count(*) from T_RHSTU_CONSULTA union all
select 'from T_RHSTU_CONSULTA_FORMA_PAGTO' as name ,count(*) from T_RHSTU_CONSULTA_FORMA_PAGTO union all
select 'from T_RHSTU_CONTATO_PACIENTE' as name ,count(*) from T_RHSTU_CONTATO_PACIENTE union all
select 'from T_RHSTU_EMAIL_PACIENTE' as name ,count(*) from T_RHSTU_EMAIL_PACIENTE union all
select 'from T_RHSTU_ENDERECO_PACIENTE' as name ,count(*) from T_RHSTU_ENDERECO_PACIENTE union all
select 'from T_RHSTU_ENDERECO_UNIDHOSP' as name ,count(*) from T_RHSTU_ENDERECO_UNIDHOSP union all
select 'from T_RHSTU_ESTADO' as name ,count(*) from T_RHSTU_ESTADO;




--MOSTRAR QUANTIDADE DE LINHAS
SELECT 'TOTAL' AS "COLUNA",
(
    (SELECT COUNT(*) FROM T_RHSTU_BAIRRO) +
    (SELECT COUNT(*) FROM T_RHSTU_CIDADE) +
    (SELECT COUNT(*) FROM T_RHSTU_CONSULTA) +
    (SELECT COUNT(*) FROM T_RHSTU_CONSULTA_FORMA_PAGTO) +
    (SELECT COUNT(*) FROM T_RHSTU_CONTATO_PACIENTE) +
    (SELECT COUNT(*) FROM T_RHSTU_EMAIL_PACIENTE) +
    (SELECT COUNT(*) FROM T_RHSTU_ENDERECO_PACIENTE) +
    (SELECT COUNT(*) FROM T_RHSTU_ENDERECO_UNIDHOSP) +
    (SELECT COUNT(*) FROM T_RHSTU_ESTADO) +
    (SELECT COUNT(*) FROM T_RHSTU_FORMA_PAGAMENTO) +
    (SELECT COUNT(*) FROM T_RHSTU_FUNCIONARIO) +
    (SELECT COUNT(*) FROM T_RHSTU_LOGRADOURO) +
    (SELECT COUNT(*) FROM T_RHSTU_MEDICAMENTO) +
    (SELECT COUNT(*) FROM T_RHSTU_MEDICO) +
    (SELECT COUNT(*) FROM T_RHSTU_MOTORISTA) +
    (SELECT COUNT(*) FROM T_RHSTU_PACIENTE) +
    (SELECT COUNT(*) FROM T_RHSTU_PACIENTE_PLANO_SAUDE) +
    (SELECT COUNT(*) FROM T_RHSTU_PLANO_SAUDE) +
    (SELECT COUNT(*) FROM T_RHSTU_PRESCRICAO_MEDICA) +
    (SELECT COUNT(*) FROM T_RHSTU_TELEFONE_PACIENTE) +
    (SELECT COUNT(*) FROM T_RHSTU_TIPO_CONTATO) +
    (SELECT COUNT(*) FROM T_RHSTU_UNID_HOSPITALAR)
) AS "QTDE REGISTROS"
FROM DUAL UNION ALL
SELECT 'T_RHSTU_BAIRRO',COUNT(*) FROM T_RHSTU_BAIRRO UNION ALL
SELECT 'T_RHSTU_CIDADE',COUNT(*) FROM T_RHSTU_CIDADE UNION ALL
SELECT 'T_RHSTU_CONSULTA',COUNT(*) FROM T_RHSTU_CONSULTA UNION ALL
SELECT 'T_RHSTU_CONSULTA_FORMA_PAGTO',COUNT(*) FROM T_RHSTU_CONSULTA_FORMA_PAGTO UNION ALL
SELECT 'T_RHSTU_CONTATO_PACIENTE',COUNT(*) FROM T_RHSTU_CONTATO_PACIENTE UNION ALL
SELECT 'T_RHSTU_EMAIL_PACIENTE',COUNT(*) FROM T_RHSTU_EMAIL_PACIENTE UNION ALL
SELECT 'T_RHSTU_ENDERECO_PACIENTE',COUNT(*) FROM T_RHSTU_ENDERECO_PACIENTE UNION ALL
SELECT 'T_RHSTU_ENDERECO_UNIDHOSP',COUNT(*) FROM T_RHSTU_ENDERECO_UNIDHOSP UNION ALL
SELECT 'T_RHSTU_ESTADO',COUNT(*) FROM T_RHSTU_ESTADO UNION ALL
SELECT 'T_RHSTU_FORMA_PAGAMENTO',COUNT(*) FROM T_RHSTU_FORMA_PAGAMENTO UNION ALL
SELECT 'T_RHSTU_FUNCIONARIO',COUNT(*) FROM T_RHSTU_FUNCIONARIO UNION ALL
SELECT 'T_RHSTU_LOGRADOURO',COUNT(*) FROM T_RHSTU_LOGRADOURO UNION ALL
SELECT 'T_RHSTU_MEDICAMENTO',COUNT(*) FROM T_RHSTU_MEDICAMENTO UNION ALL
SELECT 'T_RHSTU_MEDICO',COUNT(*) FROM T_RHSTU_MEDICO UNION ALL
SELECT 'T_RHSTU_MOTORISTA',COUNT(*) FROM T_RHSTU_MOTORISTA UNION ALL
SELECT 'T_RHSTU_PACIENTE',COUNT(*) FROM T_RHSTU_PACIENTE UNION ALL
SELECT 'T_RHSTU_PACIENTE_PLANO_SAUDE',COUNT(*) FROM T_RHSTU_PACIENTE_PLANO_SAUDE UNION ALL
SELECT 'T_RHSTU_PLANO_SAUDE',COUNT(*) FROM T_RHSTU_PLANO_SAUDE UNION ALL
SELECT 'T_RHSTU_PRESCRICAO_MEDICA',COUNT(*) FROM T_RHSTU_PRESCRICAO_MEDICA UNION ALL
SELECT 'T_RHSTU_TELEFONE_PACIENTE',COUNT(*) FROM T_RHSTU_TELEFONE_PACIENTE UNION ALL
SELECT 'T_RHSTU_TIPO_CONTATO',COUNT(*) FROM T_RHSTU_TIPO_CONTATO UNION ALL
SELECT 'T_RHSTU_UNID_H',COUNT(*) FROM T_RHSTU_UNID_HOSPITALAR;


--TOTAL DE LINHAS : 30861541 












UPDATE T_RHSTU_TELEFONE_PACIENTE SET NR_TELEFONE = '9973990998' WHERE ID_PACIENTE = 70000; 
UPDATE T_RHSTU_TELEFONE_PACIENTE SET NR_TELEFONE = '9978190991' WHERE ID_PACIENTE = 70001;
UPDATE T_RHSTU_TELEFONE_PACIENTE SET NR_TELEFONE = '9929990992' WHERE ID_PACIENTE = 70002;
UPDATE T_RHSTU_TELEFONE_PACIENTE SET NR_TELEFONE = '9975190993' WHERE ID_PACIENTE = 70003; 
UPDATE T_RHSTU_TELEFONE_PACIENTE SET NR_TELEFONE = '9975790994' WHERE ID_PACIENTE = 70004; 







DELETE FROM T_RHSTU_TELEFONE_PACIENTE WHERE ID_TELEFONE = 5000;

DELETE FROM T_RHSTU_TELEFONE_PACIENTE WHERE ID_TELEFONE = 5001;


